"""Add new models

Revision ID: d875ecc11e87
Revises: 1bc5e3d28db7
Create Date: 2024-06-20 08:31:44.356777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd875ecc11e87'
down_revision: Union[str, None] = '1bc5e3d28db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
